// <auto-generated />
using System;
using DateMe.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DateMe.Migrations
{
    [DbContext(typeof(BigChillinContext))]
    [Migration("20230214052240_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("DateMe.Models.MovieSubmission", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.ToTable("Submissions");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            Category = "Sci-Fi",
                            Director = "Christopher Nolan",
                            Edited = false,
                            LentTo = "",
                            Notes = "Masterpiece",
                            Rating = "PG-13",
                            Title = "Interstellar",
                            Year = 2014
                        },
                        new
                        {
                            MovieID = 2,
                            Category = "Romance/Satire",
                            Director = "Mike Nichols",
                            Edited = false,
                            LentTo = "",
                            Notes = "Hello Darkness",
                            Rating = "PG",
                            Title = "The Graduate",
                            Year = 1967
                        },
                        new
                        {
                            MovieID = 3,
                            Category = "Adventure",
                            Director = "Joel Crawford",
                            Edited = false,
                            LentTo = "",
                            Notes = "The most epic tale we've seen since Homer's 'Odyssey'",
                            Rating = "PG",
                            Title = "Puss in Boots: The Last Wish",
                            Year = 2022
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
